//
//  POIDefaults.swift
//  CultureHunter
//
//  Created by Domenico Di Marino on 23/07/25.
//
import Foundation


struct POIDefaults {
    static let all: [POI] = [
        POI(
            street: "Via Giuseppe Armenante",
            streetNumber: "21",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Casa mia",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.70355755997264,
            longitude: 14.690757149236486,
            imageName: "casa_mia",
            yearBuilt: "1551-1565",
        ),
        POI(
            street: "Via Lannio",
            streetNumber: "2",
            city: "Cetara",
            province: "Salerno",
            diaryPlaceName: "Torre di Cetara",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.646993,
            longitude: 14.703472,
            imageName: "torre_di_cetara",
            yearBuilt: "1551-1565",
        ),
        POI(
            street: "Castello di Arechi, Fossato degli Aragonesi",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Castello di Arechi",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.684072,
            longitude: 14.755469,
            imageName: "castello_arechi",
            yearBuilt: "VII-IX secolo, ampliamenti successivi",
        ),
        POI(
            street: "Giardino della Minerva",
            streetNumber: "1",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Giardino della Minerva",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.681106,
            longitude: 14.753674,
            imageName: "giardino_minerva",
            yearBuilt: "XIII secolo",
        ),
        POI(
            street: "Porto di Salerno, Molo Manfredi",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Porto di Salerno",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.671686,
            longitude: 14.73752,
            imageName: "porto_salerno",
            yearBuilt: "Epoca romana, ampliamenti recenti nel XX secolo",
        ),
        POI(
            street: "Chiesa di San Giorgio, Via Duomo",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Chiesa di San Giorgio",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.678821,
            longitude: 14.758956,
            imageName: "chiesa_sangiorgio",
            yearBuilt: "Origini paleocristiane, ricostruita tra X e XVII secolo",
        ),
        POI(
            street: "Piazza della Libertà",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Piazza della Libertà",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.676276,
            longitude: 14.753785,
            imageName: "piazza_liberta",
            yearBuilt: "2011-2021",
        ),
        POI(
            street: "Museo Diocesano San Matteo, Largo Plebiscito",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Museo Diocesano San Matteo",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.680618,
            longitude: 14.760391,
            imageName: "museo_diocesano_salerno",
            yearBuilt: "Sede XVII secolo, collezioni dal XII secolo",
        ),
        POI(
            street: "Cattedrale di Salerno - Duomo, Via Nicola Monterisi",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Duomo di Salerno",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.680203,
            longitude: 14.759559,
            imageName: "duomo_salerno",
            yearBuilt: "1076-1085",
        ),
        POI(
            street: "Chiesa di Saragnano",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Chiesa di Saragnano",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.68074,
            longitude: 14.73872,
            imageName: "saragnano",
            yearBuilt: "Origini medievali, ristrutturazioni successive"
        ),
        POI(
            street: "Chiesa del Monte dei Morti",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Chiesa del Monte dei Morti",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.680833,
            longitude: 14.760699,
            imageName: "chiesa_monte_morti",
            yearBuilt: "XVII secolo",
        ),
        POI(
            street: "Teatro Verdi, Piazza Matteo Luciani",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Teatro Verdi",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.67921,
            longitude: 14.75267,
            imageName: "teatro_verdi",
            yearBuilt: "1863-1872",
        ),
        POI(
            street: "Via Velia",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Acquedotto Medievale",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.679625,
            longitude: 14.764848,
            imageName: "velia",
            yearBuilt: "IX secolo",
        ),
        POI(
            street: "Museo dello Sbarco e Salerno Capitale",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Museo dello Sbarco e Salerno Capitale",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.64696,
            longitude: 14.817397,
            imageName: "museo_sbarco",
            yearBuilt: "2012",
        ),
        POI(
            street: "Museo virtuale della scuola medica salernitana",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Museo virtuale della scuola medica salernitana",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.679046,
            longitude: 14.760005,
            imageName: "museo_virtuale",
            yearBuilt: "2009",
        ),
        POI(
            street: "Museo Archeologico Provinciale, Via San Benedetto",
            streetNumber: "28",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Museo archeologico provinciale di Salerno",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.678984,
            longitude: 14.762344,
            imageName: "museo_archeologico",
            yearBuilt: "1939 (sede nell’ex convento di San Benedetto)",
        ),
        POI(
            street: "Chiesa della Santissima Annunziata, Via Luigi Einaudi",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Chiesa della Santissima Annunziata",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.679349,
            longitude: 14.753966,
            imageName: "chiesa_ssannunziata",
            yearBuilt: "XIV secolo (restauri XVII-XVIII sec.)",
        ),
        POI(
            street: "Parrocchia di San Pietro Apostolo, Corso Garibaldi",
            streetNumber: "",
            city: "Cetara",
            province: "Salerno",
            diaryPlaceName: "Parrocchia di San Pietro Apostolo",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.647154,
            longitude: 14.701637,
            imageName: "chiesa_sanpietro",
            yearBuilt: "IX-X secolo (aspetto attuale XVII-XVIII secolo)",
        ),
        POI(
            street: "Chiesa di Santa Maria di Costantinopoli, Corso di Cetara",
            streetNumber: "",
            city: "Cetara",
            province: "Salerno",
            diaryPlaceName: "Chiesa di Santa Maria di Costantinopoli",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.651264,
            longitude: 14.697518,
            imageName: "costantinopoli",
            yearBuilt: "XVII secolo",
        ),
        POI(
            street: "Piazza San Francesco",
            streetNumber: "",
            city: "Cetara",
            province: "Salerno",
            diaryPlaceName: "Chiesa di San Francesco",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.647333,
            longitude: 14.700893,
            imageName: "piazza_sanfra",
            yearBuilt: "XVII secolo",
        ),
        POI(
            street: "Fabbrica Nettuno, Corso Umberto I",
            streetNumber: "",
            city: "Cetara",
            province: "Salerno",
            diaryPlaceName: "Fabbrica Nettuno",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.646787,
            longitude: 14.700531,
            imageName: "fabbrica_nettuno",
            yearBuilt: "1950",
        ),
        POI(
            street: "Piazza Eugenio Abbro",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Monumento ai Caduti",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.700247,
            longitude: 14.706409,
            imageName: "caduti",
            yearBuilt: "1925",
        ),
        POI(
            street: "Via Alfonso Balzico",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Duomo di Cava",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.700062,
            longitude: 14.707315,
            imageName: "duomo_cava",
            yearBuilt: "XI secolo (rifacimenti XVII-XVIII secolo)",
        ),
        POI(
            street: "Via Armando Diaz",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Chiesa di San Rocco",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.700954,
            longitude: 14.707278,
            imageName: "chiesa_sanrocco",
            yearBuilt: "XVI secolo",
        ),
        POI(
            street: "Giardini di San Giovanni, Via Antonio Nigro",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Giardini di San Giovanni",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.698777,
            longitude: 14.709424,
            imageName: "giardini_sangio",
            yearBuilt: "XVII secolo (riqualificati in epoca recente)",
        ),
        POI(
            street: "Via Canonico Aniello Avallone",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Chiesa di Maria Assunta in Cielo (Purgatorio)",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.698125,
            longitude: 14.709047,
            imageName: "purgatorio",
            yearBuilt: "XVII secolo",
        ),
        POI(
            street: "Via Canale",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Santuario Francescano S.Francesco e S.Antonio",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.695865,
            longitude: 14.71005,
            imageName: "santuario",
            yearBuilt: "XVI secolo",
        ),
        POI(
            street: "Via Enrico de Marinis",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Chiesa di Santa Maria Incoronata dell'Olmo",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.695771,
            longitude: 14.711024,
            imageName: "madonna_olmo",
            yearBuilt: "Medioevo (aspetto attuale XVII-XVIII secolo)",
        ),
        POI(
            street: "Via Antonio d'Amico",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Abbazia della Santissima Trinità",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.682057,
            longitude: 14.691142,
            imageName: "abbazia",
            yearBuilt: "XI secolo",
        ),
        POI(
            street: "Strada Provinciale 75",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Chiesa dell'Avvocatella",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.685062,
            longitude: 14.703943,
            imageName: "chiesa_avvocatella",
            yearBuilt: "XVII secolo",
        ),
        POI(
            street: "Via Orilia",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Chiesa di San Lorenzo",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.701055,
            longitude: 14.714703,
            imageName: "chiesa_sanlo",
            yearBuilt: "Medioevo (successivi rifacimenti)",
        ),
        POI(
            street: "Viale Francesco Crispi",
            streetNumber: "",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Villa Comunale Falcone e Borsellino",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.700793,
            longitude: 14.70529,
            imageName: "villa_comunale",
            yearBuilt: "XX secolo",
        ),
        POI(
            street: "Via Eduardo de Filippis",
            streetNumber: "171",
            city: "Cava de' Tirreni",
            province: "Salerno",
            diaryPlaceName: "Casa del Dom",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.70847523801939,
            longitude: 14.709200325060241,
            imageName: "villa_comunale",
            yearBuilt: "2018",
        ),
        POI(
            street: "Piazzale Alberto Piccinini",
            streetNumber: "",
            city: "Salerno",
            province: "Salerno",
            diaryPlaceName: "Stadio Arechi",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.645228,
            longitude: 14.822551,
            imageName: "stadio_arechi",
            yearBuilt: "1988-1990",
        ),
        POI(
            street: "Via del Diritto",
            streetNumber: "",
            city: "Fisciano",
            province: "Salerno",
            diaryPlaceName: "UNISA Edificio E",
            isDiscovered: false,
            discoveredTitle: nil,
            photo: nil,
            photoPath: nil,
            latitude: 40.77252,
            longitude: 14.79116,
            imageName: "villa_comunale",
            yearBuilt: "1860",
        )
    ]
}
